### ISSUE TITLE
Upgrade for Liberty’s healing doesn’t work.

### ISSUE THREAD

**Issue by deterenkelt** [vaendryl/Sunrider#123]
Steam version (beta 7.1a)
I’ve bought the upgrade in the same menu where rockets are bought, it said that this would increase Liberty’s ability to heal from 300 to 500 HP, but in battle it still adds only three hundreds. Money were spent in vain ;_;

Here’s the save where you can try to heal Sola, but her ryder regains only 300 HP http://rghost.net/60449726

**Comment by vaendryl** [comment]
confirmed that it does work on my current code. maybe there's issues with older save games, not sure.

**Comment by ghost** [comment]
I started a completely new game two days ago, beta 7.2 from steam. Liberty heals for same 300 HP, only the cost is reduced to 70 points. $1000 was spent in vain again and I can’t patch Sunrider enough to endure Ryvian cruisers blows on Captain difficulty.
