### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Taknamay** [vaendryl/Sunrider#128]
Hi, do you have a reason for not having a license? Without specific licensing terms, your code defaults to "all rights reserved." Not sure if that's what you want.

I suggest GPL for copyleft or Expat (MIT) for permissive.

**Comment by Samu-kun** [comment]
The license is here.
https://github.com/vaendryl/Sunrider/blob/master/github%20license.docx

**Comment by Taknamay** [comment]
Ok, cool.
