### ISSUE TITLE
SD value is shown equal to 0 for everyone in Sunrider team

### ISSUE THREAD

**Issue by deterenkelt** [vaendryl/Sunrider#129]
Sunrider Mask of Arcadius beta 7.1a, steam release

I expected to see SD values, but they all show 0. Blue hexagons still show actual ranges, though, and messages about damage taken from laser weapons mention how much the shield absorbed.

Savegame: https://mega.co.nz/#!gkMzRaZZ!Z92gIVPlnp99jjMftaVt8vIZsSaLrKANj9Cp2211esk

**Comment by vaendryl** [comment]
haven't seen this anywhere on my full playthrough today.
