### ISSUE TITLE
Ava speaking when repair in battle is impossible due to distance(?)

### ISSUE THREAD

**Issue by deterenkelt** [vaendryl/Sunrider#131]
Sunrider Mask of Arcadius beta 7.1a, steam release

Casting repair on Blackjack causes the message from Ava ‘No enemies in range, Captain’, also no Ava image is present on the screen
Screenshot: http://i.imgur.com/3G13DH5.jpg
Savegame: https://mega.co.nz/#!It0w1QoQ!6-W0NhPd_FTtg8qd5w4r5Uv97C17PDPv_DD2Hq-sKUI

**Comment by vaendryl** [comment]
it is indeed because it's out of range. I've changed the message and out-or-range units now appear darker
