### ISSUE TITLE
Pirate Bomber moves after Icari approaches him (a glitch or a feature?)

### ISSUE THREAD

**Issue by deterenkelt** [vaendryl/Sunrider#132]
Sunrider Mask of Arcadius beta 7.1a, steam release

Move Icari in front of Sunrider — Pirate grunt below attacks her then the move of Icari is played again, and the bomber moves one tile away from her. Is this a bug or a feature of Pirate Bombers? If you point Icari to the other Bomber below, it won’t move at all. Why?
The bomber above Icari doesn’t escape if she’s in stealth mode, so I thought maybe that’s not a glitch, only looks like it.

Savegame: https://mega.co.nz/#!1wthRSDQ!MqM0VDthfRGp7-5QAN0DeA7MpSpsjpnhsGoM9HBYQCc

**Comment by vaendryl** [comment]
this sounds like a bug but I think that's fixed now.
