### ISSUE TITLE
Sunrider MoA beta 7.1a crashes randomly on the battle of Helion

### ISSUE THREAD

**Issue by deterenkelt** [vaendryl/Sunrider#134]
First strange thing you notice is when you place units on the battlefield there’s a phanotm image of that unit that appears somewhere on the filed with  a move from the left. Same phantoms appear for an active unit during the actual battle. On the second or third phase of Sunrider team, performing an attack causes a crash. No units were moving since placed.
Traceback: http://sprunge.us/gWKV
Savegame: https://mega.nz/#!sp8zFZZC!tbFyQCZc8ZqLZB4A9scQCUCSjd1K6fSblakCV2DPRvA

**Comment by vaendryl** [comment]
this is a tough one. I'll keep an eye out and see if this still happens with the newest code.

**Comment by vaendryl** [comment]
did find something like this while testing loading old save files from 7.1a into 7.2 and that issue should be fixed. not sure if it's the same but completed the game today without major issue so I think it's okay for now.
