### ISSUE TITLE
auto mode setting is inversed

### ISSUE THREAD

**Issue by vaendryl** [vaendryl/Sunrider#88]
>1. The Auto Message Speed option does the opposite of what you would expect it to do. If you make the bar large, the delay between messages in auto mode actually gets larger. Should be renamed Auto Message Delay or reworked to actually increase the speed of auto mode as you increase

**Comment by EnderShadow** [comment]
We should probably change the name of that setting since according to the renpy documents, that value is the number of seconds per every 250 characters. http://www.renpy.org/doc/html/screen_actions.html#preferences

**Comment by vaendryl** [comment]
since the text is 'hard coded' into an image changing it would require Sam to edit the image and I'm _pretty_ sure he'll not feel up to it :) 
I think I'll just ignore this.
